name: pruebas scraper BBC docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Login docker GitHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Paso 3 - Configurar la imagen docker
        run: docker build -t estebanadso/bbc-scraper:latest .
        
      - name: Paso 4 - Subir imagen a Docker Hub
        run: docker push estebanadso/bbc-scraper:latest
        
      - name: Paso 5 - Ejecutar scraper
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/ArchivosGenerados":/app/ArchivosGenerados \
            estebanadso/bbc-scraper:latest
            
      - name: Paso 6 - Guardar el commit con los archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Genera archivos CSV y base de datos desde Docker workflow'
          commit_user_name: GitHub Actions
          commit_user_email: estebanadso@github.com
          commit_author: Esteban Trujillo <estebanadso@github.com>
          file_pattern: ArchivosGenerados/*.csv ArchivosGenerados/*.db
