name: Generate CSV and DB Artifacts with GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py

      - name: Commit y push archivos generados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Genera archivos CSV y base de datos desde workflow'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          file_pattern: ArchivosGenerados/*.csv ArchivosGenerados/*.db
